function init_git_aliases
	alias gi='git init'
	alias ga='git add'
	alias gs='git status'
	alias gc='git commit -m'
	alias gcm='git commit'
	alias gp='git push'
	alias gpp='git pull'
	alias gf='git fetch'
	alias gl='git log'
	alias gcl='git clone'
	alias gr='git restore'
	alias grr='git reset'
	alias gb='git branch'
	alias gsw='git switch'
	alias gch='git checkout'
end
